# -*- coding: utf-8 -*-
"""Home.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWpCWFJdLPGYtHUxjI7rhSO2yf1vdud3
"""

import streamlit as st


st.title("Companion App")
st.markdown("Your Intelligent Assistant")

if not st.user.is_logged_in:
  st.markdown("____")
  st.subheader("Getting started")
  st.markdown("Create an account or login to manage your documents and get insights")
  if st.button("Log in/Sign up", use_container_width = True, type = "primary"):
    st.login()
else:
  if st.button("Log out", use_container_width = True):
    st.logout()
    st.markdown("___")
    st.markdown(f"### 👋 Welcome back, {st.user.name}!")
    st.markdown("## 🌟 Key Features")
    col1, col2 = st.columns(2)
    with col1:
      st.markdown("""
        ### 👥 User Management
        - **Create your primary account** to manage records
        - **Grant access** to family members,  or friends via email
        - **Control permissions** for shared access to relevant information

        ### 📄 Data Ingestion
        - **Upload PDFs** , reports, and other document
        - **Add images/screenshots** of documents or results
        - **Type notes directly**
        """)
    with col2:
      st.markdown("""
        ### 💬 Q&A Interface
        - **Ask questions** about your documents in natural language
        - **Get clarifications** on parameters
        - **Understand documents** and instructions
        - **Track trends** with AI-powered insights

        ### 🔗 Shared Access
        - **Authorized users** can log in and access shared documents
        - **Work in collaboration** - family members and friends stay informed
        - **Secure communication** about history and action plans
        """)
    st.markdown("____")
    st.markdown("## 🚀 Ready to Get Started?")
    action_col1, action_col2, action_col3 = st.columns(3)
    with action_col1:
      if st.button("💬 Ask Questions", use_container_width=True):
            st.switch_page("pages/02_Chat.py")
    with action_col2:
      if st.button("👥 Manage Access", use_container_width=True):
            st.switch_page("pages/00_Resgiter.py")
    with action_col3:
      if st.button("🔒 Manage Uploads", use_container_width=True):
            st.switch_page("pages/01_Upload.py")
    with st.expander("❓ How to Use Companion"):
        st.markdown("""
        **1. Create Your Account**: Sign up to create your admin account

        **2. Upload Documents**: Add PDFs, images, or type notes about your history

        **3. Ask Questions**: Use our AI chat to understand your documents better.

        **4. Share Access**: Invite family members or friends to collaborate in your journey

        **5. Stay Informed**: Everyone with access can chat with the documents to understand your condition
        """)