# -*- coding: utf-8 -*-
"""register.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwToTDLDzXrHbCu-ue73SyrbXDWobHsw
"""

import streamlit as st
import pandas as pd
import os
import time
from utils import (
    fetch_and_check_parent_registration,
    fetch_and_check_member_exists,
    save_parent_registration,
    save_member_information,
    parent_member_table,
    fetch_and_check_parent_member_table
)

# session state
if "is_parent_registered" not in st.session_state:
    st.session_state.is_parent_registered = False
# session state
if "is_member_registered" not in st.session_state:
    st.session_state.is_member_registered = False
if not st.user.is_logged_in:
    # message to please login with an icon
    st.markdown("⚠️ Please login to register a new user")
    st.stop()
if fetch_and_check_parent_registration(st.user.email)[0]:
    st.session_state.is_parent_registered = True
    # diplay the info in a table
    with st.sidebar:
        user_details = fetch_and_check_parent_registration(st.user.email)[1]
        print("User details:", user_details)
        st.subheader("User Details")
        st.markdown("**User Name:** " + user_details[0])
        st.markdown("**Primary Consultant:** " + user_details[1])
        st.markdown("**Contact Email:** " + user_details[2])
        if pd.notna(user_details[3]):
            st.markdown("**Other Consultants:** " + user_details[3])
        st.markdown("**Emergency Contact:** " + user_details[4])
# check if the user is a member
if fetch_and_check_member_exists(st.user.email)[0]:
    st.session_state.is_member_registered = True
st.title("Admin Register")
st.markdown("Register as a primary account holder: ")

parent_tab, family_tab = st.tabs(["Become the admin/guardian", "Add a member"])
with family_tab:
  st.markdown("## 📝 Add Companion")
  if not st.session_state.is_parent_registered:
        st.markdown("⚠️ You are not registered as a parent/guardian")
  else:
        with st.form(family_form):
          st.markdown("### 📝 Companion Information")
          member_name = st.text_input("Companion Name * ", placeholder = " Enter the companion's name")
          member_email = st.text_input("Companion Email * ", placeholder = " Enter the companion's email")
          member_illness = st.text_input("Companion Problem * ", placeholder = " Enter the companion's problem")
          member_other_info = st.text_area("Companion Other Information * ", placeholder = " Enter the companion's any other information")
          st.markdown("---")
          fam_submitted = st.form_submit_button("🚀 Complete Registration", type="primary", use_container_width=True)
          if fam_submitted:
            if member_name and member_email:
              if save_member_information(member_name, member_email, member_illness, member_other_info) and parent_member_table(st.user.sub, st.user.email, member_email):
                st.success("Companion added successfully")
                st.balloons()
              else:
                st.error("❌ Failed to add companion. Resolve errors and then retry.")
with parent_tab:
  if st.session_state.is_parent_registered:
    st.markdown("⚠️ You are already registered as a admin/parent/guardian ")
  elif st.session_state.is_member_registered:
    st.markdown("⚠️ You are already registered as a companion ")
  else:
    with st.form(registration_form):
      st.markdown("Parent/Guardian/Admin Information")
      parent_name = st.text_input("Parent/Guardian/Admin Name * ", placeholder = "Enter your full name", help = "This will be your primary account holder's name")
      primary_doctor = st.text_input("Primary Consultant Name * ", placeholder = "Mr. Smith", help = "Enter your primary consultant's name")
      other_doctors = st.text_area("Other Doctors Name * ", placeholder = "Mr. Brown", help = "List any other specialist you see regularly. One per line. ")
      st.markdown("Additional Information 📝")
      contact_email = st.text_input("Contact Email (Must be your gmail you are logged in with) * ", placeholder = "your.email@example.com", help = "Email for important notifications")
      emergency_contact = st.text_input("Emergency Contact Name and Phone * ", placeholder = "John Doe - (555) 123-4567", help = "Who should we contact in case of an emergency")
      st.markdown("---")
      submitted = st.form_submit_button("🚀 Complete Registration", type="primary", use_container_width=True)
      if submitted:
        if parent_name and primary_doctor and contact_email and emergency_contact:
          if save_parent_registration(parent_name, primary_doctor, contact_email, other_doctor, emergency_contact):
                st.success("Registration Submitted Successfully")
                st.balloons()
                time.sleep(5)
                st.return()

          st.markdown("### 📄 Registration Summary")
          st.markdown(f"**Parent/Guardian:** {parent_name}")
          st.markdown(f"**Primary Consultant:** {primary_doctor}")
          if other_doctors:
            st.markdown(f"**Other Consultants:**\n{other_doctors}")
          st.markdown(f"**Contact Email:** {contact_email}")
          if emergency_contact:
            st.markdown(f"**Emergency Contact:** {emergency_contact}")
          st.info("🔔 You can now start uploading medical documents and manage access for family members and caretakers.")
      else:
        st.error("❌ Please fill in all required fields marked with *")